name: tip_nav
environment:
  sdk: '>=3.10.8 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  mapbox_maps_flutter: ^2.19.1
  flutter_dotenv: ^6.0.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  image_picker: ^1.1.0        # LEM - for local photo demo only
  cupertino_icons: ^1.0.8