// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdbyGPnEUIdDrPKaTzpAzwsSASTHuDMZA',
    appId: '1:73077038645:web:578a256d0afc1354a01b7c',
    messagingSenderId: '73077038645',
    projectId: 'tipnav-d0b36',
    authDomain: 'tipnav-d0b36.firebaseapp.com',
    storageBucket: 'tipnav-d0b36.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdjd3PBaOIMpid3E6x8hnMgzgmaVs36BM',
    appId: '1:73077038645:android:a5c5ab1f35dac822a01b7c',
    messagingSenderId: '73077038645',
    projectId: 'tipnav-d0b36',
    storageBucket: 'tipnav-d0b36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa0f_6_dMsFNImY6zIjeB_JOYBCcOVXdI',
    appId: '1:73077038645:ios:50621257c16fe944a01b7c',
    messagingSenderId: '73077038645',
    projectId: 'tipnav-d0b36',
    storageBucket: 'tipnav-d0b36.firebasestorage.app',
    iosBundleId: 'com.example.tipNav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa0f_6_dMsFNImY6zIjeB_JOYBCcOVXdI',
    appId: '1:73077038645:ios:50621257c16fe944a01b7c',
    messagingSenderId: '73077038645',
    projectId: 'tipnav-d0b36',
    storageBucket: 'tipnav-d0b36.firebasestorage.app',
    iosBundleId: 'com.example.tipNav',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdbyGPnEUIdDrPKaTzpAzwsSASTHuDMZA',
    appId: '1:73077038645:web:934edbc962c6fb43a01b7c',
    messagingSenderId: '73077038645',
    projectId: 'tipnav-d0b36',
    authDomain: 'tipnav-d0b36.firebaseapp.com',
    storageBucket: 'tipnav-d0b36.firebasestorage.app',
  );
}
